title: Raccoin
description: >-
  Crypto Portfolio and Tax Reporting Tool.
domain: raccoin.org
baseurl: ""
url: "https://raccoin.org"
author: © Thorbjørn Lindeijer
twitter_username: thorbjorn81
github_username:  bjorn
mastodon:
 - username: bjorn
   instance: toot.berlin

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - getting-started.md
  - reference.md

show_excerpts: true

exclude:
  - CNAME
  - Cargo.lock
  - Cargo.toml
  - LICENSE
  - demo/
  - src/
  - target/
