[package]
name = "cryptotax"
version = "0.1.0"
authors = ["Thorbjørn Lindeijer <bjorn@lindeijer.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2"
serde = { version = "1.0.188", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde"] }
chrono-tz = "0.8"
serde_json = "1.0.107"
esplora-client = { version = "0.6", default-features = false, features = ["blocking"] }
bitcoin = "0.30.1"
slint = "1.2.1"
open = "5.0.0"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
cryptotax_ui = { path = "cryptotax_ui" }
slice-group-by = "0.3.1"
